### ISSUE TITLE
Todo-Items are not saved correctly

### ISSUE THREAD

**Issue by e-it** [pagekit/example-todo#1]
Hello,

unfortunately the ToDo-Items are not saved correctly. If I click "save" the items are not always saved. If I add some items they sometimes are saved, sometimes they are not.

Please have a look at http://d.pr/1iy9n .

**Comment by florianletsch** [comment]
I think I have figured out what is going on. The changes are actually properly stored in the database.

The problem arises when the default module config from the `index.php` is merged with the config stored in the database. The merging of associative arrays will sometimes mean, that an entry from the default config is kept in the array, even though the user had deleted the entry in the browser.

I don't think this is actually a bug. The merging happens according to how array_merge works in PHP and in some cases, this behaviour is expected.

My proposed change to fix this in the example extension is to remove the default entries from the `index.php` an replace them with an empty array.

**Change this**:

```
    'config' => [
        'entries' => [
            ['message' => 'Buy milk.', 'done' => false],
            ['message' => 'Read book.', 'done' => false],
            ['message' => 'Drink coffee.', 'done' => true]
        ]
    ],
```

**...to look like this:**

```
    'config' => [
        'entries' => []
    ],
```

I will change this in the example code. Thanks for pointing this out!
